/*
	names: 			Cas van der Weegen & Johan Josua Storm
	Studentnumber: 	6055338 & 6283934
	Assignment 1, april 15 2013
*/
CC=gcc
CFLAGS=-Wall -o2 -pedantic -g -std=gnu99
FILES=scanner.c func.c
PROG=scanner

all: $(FILES)
	$(CC) $(CFLAGS) -o $(PROG) $(FILES)
